openapi: 3.0.0
info:
  title: 'Milos review API'
  version: '0.1'
paths:
  /api/artists:
    get:
      operationId: 'App\Http\Controllers\ArtistController::index'
      responses:
        '200':
          description: 'Return list of artists'
